#!/usr/bin/python
import socket
import subprocess
from time import gmtime, strftime
import sys

def incoming_call(msg,addr):
    t = strftime("%a, %d %b %Y %H:%M:%S", gmtime())
    print "%s: [%s] %s" % (t,addr, msg)
    try:
        subprocess.call(["eject", "-T", "/dev/cdrom"])
        subprocess.call(["play", "-q", sys.path[0]+"/sounds/sonar.wav"])	
        subprocess.call(["eject", "-T", "/dev/cdrom"])
        subprocess.call(["notify-send", msg])
    except:
        pass

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

try: 
    s.bind(("", 50000)) 
    while True:
        if msg=="update":
            pass
 	else:
            daten, addr = s.recvfrom(1024) 
            incoming_call(daten,addr[0])
finally: 
    s.close()
