#!/usr/bin/python
import socket
import subprocess
from time import gmtime, strftime, localtime
import sys
import os

def incoming_call(msg,addr):
    t = strftime("%a, %d %b %Y %H:%M:%S", gmtime())
    print "%s: [%s] %s" % (t,addr, msg)
    try:
        subprocess.call(["eject", "-T", "/dev/cdrom"])
        subprocess.call(["play", "-q", sys.path[0]+"/sounds/sonar.wav"])	
        subprocess.call(["eject", "-T", "/dev/cdrom"])
        subprocess.call(["notify-send", msg])
    except:
        pass

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

try: 
    s.bind(("", 50000)) 
    while True:
        daten, addr = s.recvfrom(1024) 
        if daten=="update":
            t = strftime("%a, %d %b %Y %H:%M:%S", gmtime())
            print "%s: [%s] update and restart" % (t,addr)
            os.chdir(sys.path[0])
            subprocess.call(["git","pull"])
            os.execl("python","lunch_server") 
 	else:
            if localtime()[3] >= 11 and localtime()[4] >= 45 and localtime()[3] <= 12 and localtime()[4] <= 45:
                incoming_call(daten,addr[0])
finally: 
    s.close()
